<?php

/**
 * PHP version 7.1
 *
 * @category  Techeniac
 * @package   Techeniac\VideoSlider\Model\ResourceModel
 * @author    Techeniac <buzz@techeniac.com>
 * @copyright 2019 This file was generated by Techeniac
 * @license   http://www.techeniac.com Open Software License (OSL 3.0)
 * @link      http://www.techeniac.com
 */

namespace Techeniac\VideoSlider\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

/**
 * PHP version 7.1
 *
 * @category  Etatvasoft
 * @package   Techeniac\VideoSlider\Model\ResourceModel
 * @author    Techeniac <buzz@techeniac.com>
 * @copyright 2018 This file was generated by Etatvasoft
 * @license   http://etatvasoft.com  Open Software License (OSL 3.0)
 * @link      http://etatvasoft.com
 */

class Slider extends AbstractDb
{

    /**
     * Initialize
     *
     * @return Null
     */
    protected function _construct()
    {
        $this->_init('techeniac_video_slider', 'id');
    }
}
