<?php

/**
 * PHP version 7.1
 *
 * @category  Techeniac
 * @package   Techeniac\VideoSlider\Controller\Adminhtml\Slider
 * @author    Techeniac <buzz@techeniac.com>
 * @copyright 2019 This file was generated by Techeniac
 * @license   http://www.techeniac.com Open Software License (OSL 3.0)
 * @link      http://www.techeniac.com
 */
namespace Techeniac\VideoSlider\Controller\Adminhtml\Slider;

use Magento\Backend\App\Action\Context;
use Magento\Ui\Component\MassAction\Filter;
use Techeniac\VideoSlider\Model\ResourceModel\Slider\CollectionFactory;
use Magento\Framework\Filesystem;
use Magento\Framework\Controller\ResultFactory;

/**
 * PHP version 7.1
 *
 * @category  Techeniac
 * @package   Techeniac\VideoSlider\Controller\Adminhtml\Slider
 * @author    Techeniac <buzz@techeniac.com>
 * @copyright 2019 This file was generated by Techeniac
 * @license   http://www.techeniac.com Open Software License (OSL 3.0)
 * @link      http://www.techeniac.com
 */

class MassDelete extends \Magento\Backend\App\Action
{
    /**
     * Filter variable
     *
     * @var Filter
     */
    private $filter;

    /**
     * CollectionFactory variable
     *
     * @var CollectionFactory
     */
    private $collectionFactory;

    /**
     * FileSystem variable
     *
     * @var FileSystem
     */
    private $fileSystem;

    /**
     * Initialize
     *
     * @param Context           $context           Initialize context
     * @param Filter            $filter            Initialize filter
     * @param CollectionFactory $collectionFactory Initialize Collectionfactory
     */
    public function __construct(
        Context $context,
        Filter $filter,
        CollectionFactory $collectionFactory,
        Filesystem $fileSystem
    ) {
        $this->filter = $filter;
        $this->collectionFactory = $collectionFactory;
        $this->fileSystem = $fileSystem;
        parent::__construct($context);
    }
    /**
     * Execute action
     *
     * @return \Magento\Backend\Model\View\Result\Redirect
     * @throws \Magento\Framework\Exception\LocalizedException|\Exception
     */
    public function execute()
    {
        $collection = $this->filter
            ->getCollection($this->collectionFactory->create());
        $collectionSize = $collection->getSize();

        foreach ($collection as $item) {
            //Delete Image From folder
            $filename = $item->getFile();
            $fileSystem = $this->fileSystem;
            $mediaPath = $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath('/videoslider/');
            @unlink($mediaPath.$filename);
            $item->delete();
        }

        $this->messageManager->addSuccess(
            __(
                'A total of %1 record(s) have been deleted.',
                $collectionSize
            )
        );

        /**
         * Redirect to page
         *
         * @var \Magento\Backend\Model\View\Result\Redirect $resultRedirect
         */
        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        return $resultRedirect->setPath('*/*/');
    }
}
