<?php

/**
 * PHP version 7.1
 *
 * @category  Techeniac
 * @package   Techeniac\VideoSlider\Controller\Adminhtml\Slider
 * @author    Techeniac <buzz@techeniac.com>
 * @copyright 2019 This file was generated by Techeniac
 * @license   http://www.techeniac.com Open Software License (OSL 3.0)
 * @link      http://www.techeniac.com
 */
namespace Techeniac\VideoSlider\Controller\Adminhtml\Slider;

/**
 * PHP version 7.1
 *
 * @category  Techeniac
 * @package   Techeniac\VideoSlider\Controller\Adminhtml\Slider
 * @author    Techeniac <buzz@techeniac.com>
 * @copyright 2019 This file was generated by Techeniac
 * @license   http://www.techeniac.com Open Software License (OSL 3.0)
 * @link      http://www.techeniac.com
 */

class NewAction extends \Magento\Backend\App\Action
{
    /**
     * ResultForwardFactory
     *
     * @var \Magento\Backend\Model\View\Result\Forward
     */
    private $resultForwardFactory;

    /**
     * Initialization
     *
     * @param Action\Context $context              Initialize context
     * @param ForwardFactory $resultForwardFactory Initialize Forwardfactory
     */
    public function __construct(
        \Magento\Backend\App\Action\Context $context,
        \Magento\Backend\Model\View\Result\ForwardFactory $resultForwardFactory
    ) {
        $this->resultForwardFactory = $resultForwardFactory;
        parent::__construct($context);
    }

    /**
     * {@inheritdoc}
     *
     * @return NUll
     */
    public function _isAllowed()
    {
        return $this->_authorization->isAllowed('Techeniac_VideoSlider::save');
    }

    /**
     * Forward to edit
     *
     * @return \Magento\Backend\Model\View\Result\Forward
     */
    public function execute()
    {
        /**
         * Execute Method
         *
         * @var    \Magento\Backend\Model\View\Result\Forward $resultForward
         * @return path
         */
        $resultForward = $this->resultForwardFactory->create();
        return $resultForward->forward('edit');
    }
}
